version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    pull-request-branch-name: "deps/{{dependencyName}}-{{newVersion}}"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
      - "automated PR"